apiVersion: v1
kind: Service
metadata:
  name: angular-frontend
spec:
  type: NodePort
  selector:
    app: angular-frontend
  ports:
    - port: 4200
      targetPort: 4200
      nodePort: 30014
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-frontend
  labels:
    app: angular-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-frontend
  template:
    metadata:
      labels:
        app: angular-frontend
    spec:
      containers:
        - name: flutter-web
          image: rihabbennour/angular-frontend:latest
          ports:
            - containerPort: 4200
